/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2024-06-13 01:51:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Gson</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\" integrity=\"sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<h1>AJAX 요청 후 scream을 이용한 JSON 응답 (gson library)</h1>\r\n");
      out.write("\r\n");
      out.write("	<h3>1. 데이터 전송 없이 json 반환</h3>\r\n");
      out.write("	<button id=\"send-get-1\">SEND</button>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(\"#send-get-1\").click(function(){\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url: \"/chap05/gson/test1\",\r\n");
      out.write("				type: \"get\",\r\n");
      out.write("				success: function(data){\r\n");
      out.write("					console.table(data);\r\n");
      out.write("				},\r\n");
      out.write("				error: function(error){\r\n");
      out.write("					console.log(errer);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<hr>\r\n");
      out.write("	\r\n");
      out.write("	memberCode: <input type=\"text\" id=\"memberCode\"><br>\r\n");
      out.write("	memberName: <input type=\"text\" id=\"name\"><br>\r\n");
      out.write("	gender: <input type=\"text\" id=\"gender\"><br>\r\n");
      out.write("	age: <input type=\"number\" id=\"age\"><br>\r\n");
      out.write("	enrollDate: <input type=\"date\" id=\"enrollDate\"><br>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<h3>2. 기본 자료형 데이터 전송 후 json 반환</h3>\r\n");
      out.write("	<button id=\"send-get-2\">기본 자료형 데이터 SEND</button>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(\"#send-get-2\").click(function(){\r\n");
      out.write("			const memberCode = $(\"#memberCode\").val();   // jquery 버전\r\n");
      out.write("			const name = document.getElementById(\"name\").value;   // javascript 버전\r\n");
      out.write("			const gender = $(\"#gender\").val();\r\n");
      out.write("			const age = document.getElementById(\"age\").value;\r\n");
      out.write("			const enrollDate = $(\"#enrollDate\").val();\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url: \"/chap05/gson/test2\",\r\n");
      out.write("				type: \"get\",\r\n");
      out.write("				date: {\r\n");
      out.write("					memberCode: memberCode,\r\n");
      out.write("					name: name,\r\n");
      out.write("					gender: gender,\r\n");
      out.write("					age: age,\r\n");
      out.write("					enrollDate: enrollDate\r\n");
      out.write("				},\r\n");
      out.write("				success: function(data){\r\n");
      out.write("					console.table(data);\r\n");
      out.write("				},\r\n");
      out.write("				error: function(error){\r\n");
      out.write("					console.log(error);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<h3>3. Object 타입의 데이터 전송 후 json 반환</h3>\r\n");
      out.write("	<button id=\"send-get-3\">객체 타입의 데이터 SEND</button>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(\"#send-get-3\").click(function(){\r\n");
      out.write("			const memberCode = $(\"#memberCode\").val();   // jquery 버전\r\n");
      out.write("			const name = document.getElementById(\"name\").value;   // javascript 버전\r\n");
      out.write("			const gender = $(\"#gender\").val();\r\n");
      out.write("			const age = document.getElementById(\"age\").value;\r\n");
      out.write("			const enrollDate = $(\"#enrollDate\").val();\r\n");
      out.write("			\r\n");
      out.write("			const member = {\r\n");
      out.write("					memberCode: memberCode,\r\n");
      out.write("					name: name,\r\n");
      out.write("					gender: gender,\r\n");
      out.write("					age: age,\r\n");
      out.write("					enrollDate: enrollDate\r\n");
      out.write("			};\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url: \"/chap05/gson/test2\",\r\n");
      out.write("				type: \"get\",\r\n");
      out.write("				data: member,\r\n");
      out.write("				success: function(data){\r\n");
      out.write("					console.table(data);\r\n");
      out.write("				},\r\n");
      out.write("				error: function(error){\r\n");
      out.write("					console.log(error);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<h3>4. json 문자열 전송 후 json 반환</h3>\r\n");
      out.write("	<button id=\"send-get-4\">객체 타입의 데이터 SEND</button>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(\"#send-get-4\").click(function(){\r\n");
      out.write("			const memberCode = $(\"#memberCode\").val();   // jquery 버전\r\n");
      out.write("			const name = document.getElementById(\"name\").value;   // javascript 버전\r\n");
      out.write("			const gender = $(\"#gender\").val();\r\n");
      out.write("			const age = document.getElementById(\"age\").value;\r\n");
      out.write("			const enrollDate = $(\"#enrollDate\").val();\r\n");
      out.write("			\r\n");
      out.write("			const member = {\r\n");
      out.write("					memberCode: memberCode,\r\n");
      out.write("					name: name,\r\n");
      out.write("					gender: gender,\r\n");
      out.write("					age: age,\r\n");
      out.write("					enrollDate: enrollDate\r\n");
      out.write("			};\r\n");
      out.write("			\r\n");
      out.write("			const jsonString = JSON.stringify(member);\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url: \"/chap05/gson/test3\",\r\n");
      out.write("				type: \"get\",\r\n");
      out.write("				data: { jsonString },   // == { jsonString: jsonString }\r\n");
      out.write("				success: function(data){\r\n");
      out.write("					console.table(data);\r\n");
      out.write("				},\r\n");
      out.write("				error: function(error){\r\n");
      out.write("					console.log(error);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<h3>5. GsonBuilder 테스트</h3>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
