USE boardproject;

DROP TABLE IF EXISTS TBL_NOTICE;


CREATE TABLE TBL_NOTICE (
	NOTICE_NO INT AUTO_INCREMENT PRIMARY KEY,
	NOTICE_TITLE VARCHAR(100) NOT NULL,
	NOTICE_BODY VARCHAR(4000) NOT NULL,
	NOTICE_ENROLL_DATE TIMESTAMP,
	NOTICE_MODIFY_DATE TIMESTAMP,
	NOTICE_COUNT INT DEFAULT 0,
	NOTICE_BOARD_STATUS VARCHAR(2) DEFAULT 'Y',
	NOTICE_USER_NO INT NOT NULL,
  FOREIGN KEY (NOTICE_USER_NO) REFERENCES TBL_USER (USER_NO)
);

SELECT * FROM TBL_NOTICE;