-- DB에 추가 시 계정 추가
CREATE DATABASE sessionauth;
-- CREATE USER 'songpa'@'%' IDENTIFIED BY  'songpa'; 
GRANT ALL PRIVILEGES ON sessionauth.* TO 'songpa'@'%';

USE sessionauth;

-- 기존 테이블 삭제
DROP TABLE IF EXISTS TBL_MEMBER;

-- TABLE 생성
-- MEMBER 테이블 생성
CREATE TABLE TBL_MEMBER(
  MEMBER_NO INT AUTO_INCREMENT PRIMARY KEY,
  MEMBER_ID VARCHAR(20) UNIQUE,
  MEMBER_PWD VARCHAR(255) NOT NULL,
  NICKNAME VARCHAR(255) NOT NULL,
  PHONE VARCHAR(20),
  EMAIL VARCHAR(50),
  ADDRESS VARCHAR(255),
  ENROLL_DATE DATE,
  MEMBER_ROLE VARCHAR(15) DEFAULT 'ROLE_MEMBER' CHECK(MEMBER_ROLE IN ('ROLE_MEMBER', 'ROLE_ADMIN')),
  MEMBER_STATUS VARCHAR(2) DEFAULT 'Y'
);
